<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="6" total="10" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-22T13:53:23 IST" name="Default suite" finished-at="2024-11-22T13:54:01 IST" duration-ms="37780">
    <groups>
    </groups>
    <test started-at="2024-11-22T13:53:23 IST" name="Default test" finished-at="2024-11-22T13:54:01 IST" duration-ms="37780">
      <class name="com.sevenrmartsupermarket.tests.SubcategoryTest">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:23 IST" name="launchBrowser" finished-at="2024-11-22T13:53:29 IST" duration-ms="6122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method retried="true" signature="verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:29 IST" name="verifyInvalidSearchUsingRetryAnalyzer" finished-at="2024-11-22T13:53:34 IST" duration-ms="4933" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sevenrmartsupermarket.tests.SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer(SubcategoryTest.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidSearchUsingRetryAnalyzer -->
        <test-method is-config="true" signature="terminateBrowser(org.testng.ITestResult)[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:34 IST" name="terminateBrowser" finished-at="2024-11-22T13:53:34 IST" duration-ms="265" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyInvalidSearchUsingRetryAnalyzer status=SKIP method=SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:34 IST" name="launchBrowser" finished-at="2024-11-22T13:53:39 IST" duration-ms="4658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method retried="true" signature="verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:39 IST" name="verifyInvalidSearchUsingRetryAnalyzer" finished-at="2024-11-22T13:53:42 IST" duration-ms="3139" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sevenrmartsupermarket.tests.SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer(SubcategoryTest.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidSearchUsingRetryAnalyzer -->
        <test-method is-config="true" signature="terminateBrowser(org.testng.ITestResult)[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:42 IST" name="terminateBrowser" finished-at="2024-11-22T13:53:42 IST" duration-ms="247" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyInvalidSearchUsingRetryAnalyzer status=SKIP method=SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:42 IST" name="launchBrowser" finished-at="2024-11-22T13:53:48 IST" duration-ms="5207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method retried="true" signature="verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:48 IST" name="verifyInvalidSearchUsingRetryAnalyzer" finished-at="2024-11-22T13:53:52 IST" duration-ms="4789" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sevenrmartsupermarket.tests.SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer(SubcategoryTest.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidSearchUsingRetryAnalyzer -->
        <test-method is-config="true" signature="terminateBrowser(org.testng.ITestResult)[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:52 IST" name="terminateBrowser" finished-at="2024-11-22T13:53:53 IST" duration-ms="214" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyInvalidSearchUsingRetryAnalyzer status=SKIP method=SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:53 IST" name="launchBrowser" finished-at="2024-11-22T13:53:57 IST" duration-ms="4414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:53:57 IST" name="verifyInvalidSearchUsingRetryAnalyzer" finished-at="2024-11-22T13:54:00 IST" duration-ms="3160" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [RESULT NOT FOUND] but found [.........RESULT NOT FOUND.......]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sevenrmartsupermarket.tests.SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer(SubcategoryTest.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidSearchUsingRetryAnalyzer -->
        <test-method is-config="true" signature="terminateBrowser(org.testng.ITestResult)[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20]" started-at="2024-11-22T13:54:00 IST" name="terminateBrowser" finished-at="2024-11-22T13:54:01 IST" duration-ms="538" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyInvalidSearchUsingRetryAnalyzer status=FAILURE method=SubcategoryTest.verifyInvalidSearchUsingRetryAnalyzer()[pri:0, instance:com.sevenrmartsupermarket.tests.SubcategoryTest@45d84a20] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- com.sevenrmartsupermarket.tests.SubcategoryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
